use_frameworks!
platform :ios, '8.0'

target 'Flower' do

pod 'Alamofire', '~> 3.4' ## 网络请求, swift版的AFN
pod 'Kingfisher', '~> 2.3.1' ## 轻量级的SDWebImage
pod 'MBProgressHUD', '~> 0.9.2' ##
pod 'MJRefresh', '~> 3.1.10' ##刷新

end
